name: adsdb

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - ${S3_API_ENDPOINT}:9000 # MinIO Api 
      - 127.0.0.1:9001:9001 # MinIO Console
    command: server /data --console-address=":9001"
    environment:
      MINIO_ROOT_USER: ${ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${SECRET_ACCESS_KEY}
    volumes:
      - minio-data:/data
  chromadb:
    image: ghcr.io/chroma-core/chroma # Official ChromaDB image
    ports:
      - "8000:8000" # Expose ChromaDB API on port 8000
    volumes:
      - chroma-data:/chroma # Persist ChromaDB data

volumes:
  chroma-data:
  minio-data:
